"""align schema with extract contract

Revision ID: 0b0c7852a1d2
Revises: 12d5bc689267
Create Date: 2026-09-02 20:59:24.988607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b0c7852a1d2'
down_revision: Union[str, Sequence[str], None] = '12d5bc689267'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artworks', sa.Column('highlight', sa.Boolean(), server_default=sa.false(), nullable=False))
    op.add_column('artworks', sa.Column('classification', sa.Text(), nullable=True))
    op.add_column('artworks', sa.Column('name', sa.Text(), nullable=True))
    op.add_column('artworks', sa.Column('year_end', sa.Integer(), nullable=True))
    op.add_column('artworks', sa.Column('artist_role', sa.Text(), nullable=True))
    op.add_column('artworks', sa.Column('artist_bio', sa.Text(), nullable=True))
    op.add_column('artworks', sa.Column('artist_nationality', sa.Text(), nullable=True))
    op.add_column('artworks', sa.Column('artist_birth', sa.Text(), nullable=True))
    op.add_column('artworks', sa.Column('artist_death', sa.Text(), nullable=True))
    op.add_column('artworks', sa.Column('city', sa.Text(), nullable=True))
    op.add_column('artworks', sa.Column('state', sa.Text(), nullable=True))
    op.add_column('artworks', sa.Column('county', sa.Text(), nullable=True))
    op.add_column('artworks', sa.Column('country', sa.Text(), nullable=True))
    op.add_column('artworks', sa.Column('region', sa.Text(), nullable=True))
    op.add_column('artworks', sa.Column('subregion', sa.Text(), nullable=True))
    op.add_column('artworks', sa.Column('rights', sa.Text(), nullable=True))
    op.add_column('artworks', sa.Column('link', sa.Text(), nullable=True))
    op.add_column('artworks', sa.Column('accession_year', sa.Integer(), nullable=True))
    op.alter_column('artworks', 'title', existing_type=sa.TEXT(), nullable=True)
    op.alter_column('artworks', 'medium', existing_type=sa.TEXT(), nullable=True)
    op.alter_column('artworks', 'date', existing_type=sa.TEXT(), nullable=True)
    op.alter_column('artworks', 'credit_line', existing_type=sa.TEXT(), nullable=True)
    op.alter_column('artworks', 'object_id', new_column_name='id')
    op.alter_column('artworks', 'maker', new_column_name='artist_name')
    op.alter_column('artworks', 'object_number', new_column_name='number')
    op.alter_column('artworks', 'curatorial_department', new_column_name='department')
    op.drop_column('artworks', 'geography')
    op.alter_column('artworks', 'highlight', server_default=None)
    op.execute("UPDATE artworks SET link = 'http://www.metmuseum.org/art/collection/search/' || id")
    op.alter_column('artworks', 'link', nullable=False)
    op.execute("UPDATE artworks SET year_end = year_start WHERE year_end IS NULL")
    op.alter_column('artworks', 'year_end', nullable=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artworks', 'accession_year')
    op.drop_column('artworks', 'link')
    op.drop_column('artworks', 'rights')
    op.drop_column('artworks', 'subregion')
    op.drop_column('artworks', 'region')
    op.drop_column('artworks', 'country')
    op.drop_column('artworks', 'county')
    op.drop_column('artworks', 'state')
    op.drop_column('artworks', 'city')
    op.drop_column('artworks', 'artist_death')
    op.drop_column('artworks', 'artist_birth')
    op.drop_column('artworks', 'artist_nationality')
    op.drop_column('artworks', 'artist_bio')
    op.drop_column('artworks', 'artist_role')
    op.drop_column('artworks', 'year_end')
    op.drop_column('artworks', 'name')
    op.drop_column('artworks', 'classification')
    op.drop_column('artworks', 'highlight')
    op.alter_column('artworks', 'id', new_column_name='object_id')
    op.alter_column('artworks', 'artist_name', new_column_name='maker')
    op.alter_column('artworks', 'number', new_column_name='object_number')
    op.alter_column('artworks', 'department', new_column_name='curatorial_department')
    op.alter_column('artworks', 'credit_line', existing_type=sa.TEXT(), nullable=False)
    op.alter_column('artworks', 'date', existing_type=sa.TEXT(), nullable=False)
    op.alter_column('artworks', 'medium', existing_type=sa.TEXT(), nullable=False)
    op.alter_column('artworks', 'title', existing_type=sa.TEXT(), nullable=False)
    op.add_column('artworks', sa.Column('geography', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
