"""widen object_number, drop unique constraint

Revision ID: 12d5bc689267
Revises: 8eb0374b6e64
Create Date: 2026-09-01 20:44:46.335751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12d5bc689267'
down_revision: Union[str, Sequence[str], None] = '8eb0374b6e64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('artworks', 'object_number',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.Text(),
               existing_nullable=False)
    op.drop_constraint(op.f('artworks_object_number_key'), 'artworks', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('artworks_object_number_key'), 'artworks', ['object_number'], postgresql_nulls_not_distinct=False)
    op.alter_column('artworks', 'object_number',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
    # ### end Alembic commands ###
    
# Two things to note for downgrade:
# 1. the text -> varchar conversion will fail if there are any object_number values longer than 32 characters. You may need to truncate or otherwise handle those values before downgrading.
# 2. the unique constraint will fail if there are any duplicate object_number values. You may need to remove duplicates before downgrading.