"""create artworks table

Revision ID: 8eb0374b6e64
Revises: 
Create Date: 2026-09-01 20:28:57.364252

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8eb0374b6e64'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artworks',
    sa.Column('object_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('object_number', sa.String(length=32), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('maker', sa.Text(), nullable=True),
    sa.Column('date', sa.Text(), nullable=False),
    sa.Column('year_start', sa.Integer(), nullable=False),
    sa.Column('geography', sa.Text(), nullable=True),
    sa.Column('culture', sa.Text(), nullable=True),
    sa.Column('medium', sa.Text(), nullable=False),
    sa.Column('dimensions', sa.Text(), nullable=True),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('width_cm', sa.Float(), nullable=True),
    sa.Column('depth_cm', sa.Float(), nullable=True),
    sa.Column('credit_line', sa.Text(), nullable=False),
    sa.Column('curatorial_department', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('object_id'),
    sa.UniqueConstraint('object_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('artworks')
    # ### end Alembic commands ###
